# Generated by Django 4.1.6 on 2023-02-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/book/")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=80)),
                ("quantity", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
