# Generated by Django 4.1.6 on 2023-02-16 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_bookissue_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookissue",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 2, 19, 53, 51, 69023)
            ),
        ),
    ]
